---
title: "Untitled"
output: html_document
date: "2023-04-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("arules")  # association rules
install.packages("arulesViz")  # association rules visualisation
install.packages("babynames")  # data for babynames
install.packages("caret")  # Machine Learning framework
install.packages("caTools")  # basic functionality
install.packages("caretEnsemble")  # ensemble learning
install.packages("cluster")  # cluster analysis
install.packages("corrplot")  # correlation plots
install.packages("datasets")  # includes some datasets we will work with
install.packages("dbscan")  # dbscan algorithm
install.packages("dendextend")  # extended dendrograms
install.packages("devtools")  # for package installation outside CRAN
install.packages("dplyr")  # data manipulation
install.packages("e1071")  # machine learning algorithms
install.packages("factoextra")  # factor analysis
install.packages("ggplot2")  # visualisation
install.packages("glmnet")  # regularization
install.packages("keras")  # deep learning
install.packages("lava")  # 
install.packages("pROC")  # ROC curve
install.packages("randomForest")  # Random Forest algorithm
install.packages("rattle")  # machine learning algorithm
install.packages("readr")  # data import
install.packages("rpart")  # Decision Trees
install.packages("rpart.plot")  # visualise Decision Trees
install.packages("stats")  # statistical methods
install.packages("tibble")  # data manipulation
install.packages("tidyr")
install.packages("remotes")
remotes::install_github("vqv/ggbiplot")
```

```{r}

```

